# Generated by Django 3.0.2 on 2020-01-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('supplier_name', models.CharField(max_length=50)),
                ('is_published', models.BooleanField()),
                ('selling_price', models.FloatField()),
                ('buying_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('average_products_price', models.FloatField()),
                ('products', models.ManyToManyField(related_name='products', to='api.Product')),
            ],
        ),
    ]
