# Generated by Django 3.0.2 on 2020-01-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200118_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='average_products_price',
        ),
    ]
